solve the task
esidarapp/spring pull request #1
Opened 2024-06-07 17:16 UTC by esidarapp

2024-06-07 18:12 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments

2024-06-07 18:12 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/service/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-06-07 18:12 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/service/BookServiceImpl.java
> +    private BookRepository bookRepository;
```suggestion
    private final BookRepository bookRepository;
```

2024-06-07 18:12 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/service/BookServiceImpl.java
> +    @Autowired
```suggestion
```

2024-06-07 18:12 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't insert book into DB: " + book);
```suggestion
            throw new DataProcessingException("Can't insert book into DB: " + book);

```
It's better to create custom exception

2024-06-07 18:12 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't get all books", e);
```suggestion
            throw new DataProcessingException("Can't get all books", e);

```

2024-06-07 18:12 UTC, Elena-Bruyako commented on src/test/resources/application.properties
> +spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
```suggestion
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

```

2024-06-07 18:12 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/repository/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-06-07 18:12 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/repository/BookRepositoryImpl.java
> +    public BookRepositoryImpl(SessionFactory sessionFactory) {
remove constructor

2024-06-08 12:30 UTC, okuzan approved these changes

2024-06-08 12:30 UTC, okuzan commented on src/main/resources/application.properties
> +
```suggestion
```

2024-06-11 05:20 UTC, Elena-Bruyako commented
<img width="943" alt="Screenshot 2024-06-11 at 08 18 54" src="https://github.com/esidarapp/spring/assets/14053156/93bf3873-5b60-4409-a28d-6d434d2a97ba">
Your changes were approved, create new PR with HW implementation and send it, don't mix up your HWs in one PR

2024-06-23 13:37 UTC, merged