added tests for book and category repo, service and controller
esidarapp/spring pull request #14
Opened 2024-07-27 11:08 UTC by esidarapp

2024-07-27 11:15 UTC, esidarapp commented
![image](https://github.com/user-attachments/assets/4eddf47a-4b86-42ae-9a52-d1a26e7c13da)
![image](https://github.com/user-attachments/assets/35d49ba1-b084-47f6-a015-c200695305e8)

2024-07-27 11:16 UTC, esidarapp commented
I think there is some error with coverage in my intellij

2024-07-29 11:01 UTC, MentorMateAcademy requested changes

2024-07-29 11:01 UTC, MentorMateAcademy commented on src/main/java/com/example/spring/dto/book/BookDto.java
> +    }
why you don`t use lombok implementation instead of this?

2024-07-29 11:01 UTC, MentorMateAcademy commented on src/test/java/com/example/spring/config/CustomMySqlContainer.java
> +    }
here no implementation?

2024-07-29 11:01 UTC, MentorMateAcademy commented on src/test/java/com/example/spring/controller/BookControllerTest.java
> +                result.getResponse().getContentAsByteArray(), BookDto[].class);
why do you parse to array instead of object?

2024-07-29 11:01 UTC, MentorMateAcademy commented on src/test/java/com/example/spring/repository/book/BookRepositoryTest.java
> +        Assertions.assertTrue(existedBook.isPresent(), "The book should be found");
assertions should be in the end

2024-07-29 11:01 UTC, MentorMateAcademy commented on src/test/java/com/example/spring/repository/book/filter/BookSpecificationBuilderTest.java
> +        assertNotNull(spec);
add more detail checks

2024-07-29 11:01 UTC, MentorMateAcademy commented on src/test/java/com/example/spring/repository/book/filter/bookprovider/AuthorSpecificationProviderTest.java
> +        Assertions.assertEquals("author", key);
save strings to constants and reuse it in tests

2024-07-29 11:01 UTC, MentorMateAcademy commented on src/test/java/com/example/spring/repository/book/filter/bookprovider/TitleSpecificationProviderTest.java
> +        Assertions.assertEquals("title", key);
save strings to constants and reuse them

2024-07-29 18:40 UTC, esidarapp commented on src/test/java/com/example/spring/controller/BookControllerTest.java
> +                result.getResponse().getContentAsByteArray(), BookDto[].class);
Should parse the response as an array because the search endpoint returns a list of books, not a single book object.

2024-07-31 09:48 UTC, okuzan approved these changes

2024-07-31 09:51 UTC, merged