Search adding
esidarapp/spring pull request #4
Opened 2024-06-19 01:29 UTC by esidarapp

2024-06-19 06:33 UTC, Elena-Bruyako requested changes
Good job! Let's improve it!

2024-06-19 06:33 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/model/Book.java
> +    @Column(name = "cover_image")
```suggestion

```
Hibernate automatically create name with snake_case

2024-06-19 06:33 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/repository/book/AuthorSpecificationProvider.java
> +        return "author";
Create constant for "author"

2024-06-19 06:33 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/repository/book/IsbnSpecificationProvider.java
> +        return "isbn";
the same

2024-06-19 06:33 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/repository/book/TitleSpecificationProvider.java
> +        return "title";
the same

2024-06-19 06:33 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +
A lot of blank lines at the end, leave just one

2024-06-19 06:33 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false

```

2024-06-19 06:33 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
```suggestion
      file: db/changelog/changes/01-create-books-table.yaml

```

2024-06-19 06:33 UTC, Elena-Bruyako commented on src/main/java/com/example/spring/repository/BookSpecificationBuilder.java
> +package com.example.spring.repository;
Let's create package filter for example, and replcae all searching logic there

2024-06-21 11:56 UTC, okuzan requested changes

2024-06-21 11:56 UTC, okuzan commented on src/main/java/com/example/spring/service/BookServiceImpl.java
> +        );
repeated logic, extract to a private method

2024-06-21 11:56 UTC, okuzan commented on src/main/java/com/example/spring/service/BookServiceImpl.java
> +    }
btw you can do it in Mapstruct mapper to - just declare list to list mapping

2024-06-22 12:57 UTC, okuzan approved these changes

2024-06-23 13:40 UTC, merged